nginx:
  image: nginx
  links:
    - php
  volumes:
    - ./main:/www  #папка с проектом
    - ./docker/nginx/conf.d:/etc/nginx/conf.d # - advanced
    #- ./docker/nginx/conf.d:/etc/nginx/conf.d-basic # - basic
  ports:
    - 80:80
    - 8080:8080
    - 443:443
php:
  build: docker/php/build
  links:
    - mysql
  volumes:
    - ./main:/www    #папка с проектом
    - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
    - ./docker/php/ini/zcustom.ini:/usr/local/etc/php/conf.d/zcustom.ini
  working_dir: /www/

mysql:
  volumes:
    - ./db:/var/lib/mysql
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: 12345
    MYSQL_DATABASE: test
  command: mysqld --sql_mode=""
  ports:
    - 3306:3306